codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 50%       # umbral mínimo
        threshold: 0.5%   # tolerancia
        informational: false
    patch:
      default:
        target: 50%
        threshold: 0%
        informational: false

ignore:
  - "**/*_mock.go"
  - "**/vendor/**"
  - "**/*.pb.go"
  - "**/generated/**"
  - "**/bin/**"
