// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/camiones": {
            "get": {
                "description": "Obtiene una lista de todos los camiones con información de tipo y estado mediante JOINs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Camiones"
                ],
                "summary": "Obtener todos los camiones",
                "responses": {
                    "200": {
                        "description": "Lista de camiones obtenida exitosamente",
                        "schema": {
                            "$ref": "#/definitions/services.CamionesResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/camiones/{id}": {
            "get": {
                "description": "Obtiene la información completa de un camión específico mediante su ID, incluyendo tipo y estado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Camiones"
                ],
                "summary": "Obtener un camión por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del camión",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Camión obtenido exitosamente",
                        "schema": {
                            "$ref": "#/definitions/services.CamionResponse"
                        }
                    },
                    "400": {
                        "description": "ID de camión inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Camión no encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/centros": {
            "get": {
                "description": "Obtiene una lista de todos los centros con información de tipo (MySQL) y datos adicionales como nombre, barrio, dirección, coordenadas (Neo4j)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Centros"
                ],
                "summary": "Obtener todos los centros",
                "responses": {
                    "200": {
                        "description": "Lista de centros obtenida exitosamente",
                        "schema": {
                            "$ref": "#/definitions/services.CentrosResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/centros/{id}": {
            "get": {
                "description": "Obtiene la información completa de un centro específico mediante su ID, incluyendo tipo (MySQL) y datos adicionales como nombre, barrio, dirección, coordenadas (Neo4j)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Centros"
                ],
                "summary": "Obtener un centro por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del centro",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Centro obtenido exitosamente",
                        "schema": {
                            "$ref": "#/definitions/services.CentroResponse"
                        }
                    },
                    "400": {
                        "description": "ID de centro inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Centro no encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/enviar-emergencia": {
            "post": {
                "description": "Registra una nueva emergencia en el sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Emergencias"
                ],
                "summary": "Enviar emergencia",
                "parameters": [
                    {
                        "description": "Datos de la emergencia",
                        "name": "emergencia",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Emergencia enviada correctamente",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResponseBody"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/personas": {
            "get": {
                "description": "Devuelve la lista completa de personas con sus asignaciones",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Personas"
                ],
                "summary": "Obtener todas las personas",
                "responses": {
                    "200": {
                        "description": "Lista de personas",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.PersonaResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/personas/zona/{zona}": {
            "get": {
                "description": "Devuelve todas las personas asignadas a una zona específica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Personas"
                ],
                "summary": "Obtener personas por zona",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número de zona",
                        "name": "zona",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Personas de la zona",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.PersonaResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/personas/{id}": {
            "get": {
                "description": "Devuelve los datos de una persona específica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Personas"
                ],
                "summary": "Obtener persona por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la persona",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Datos de la persona",
                        "schema": {
                            "$ref": "#/definitions/handlers.PersonaResponse"
                        }
                    },
                    "404": {
                        "description": "Persona no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ruta-optima": {
            "get": {
                "description": "Devuelve la ruta óptima y distancias para la zona de la persona asociada al email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rutas"
                ],
                "summary": "Obtener ruta óptima por email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email del usuario",
                        "name": "email",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de puntos con distancias",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "400": {
                        "description": "Email faltante o inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Usuario o persona no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ruta-optima/{zonaID}": {
            "get": {
                "description": "Devuelve la ruta óptima y distancias para una zona específica",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rutas"
                ],
                "summary": "Obtener ruta óptima",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la zona",
                        "name": "zonaID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de puntos con distancias",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "400": {
                        "description": "zonaID inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tachos": {
            "get": {
                "description": "Devuelve todos los tachos con barrio, dirección, latitud, longitud, estado y capacidad",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tachos"
                ],
                "summary": "Obtener todos los tachos",
                "responses": {
                    "200": {
                        "description": "Lista de todos los tachos",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/services.TachoCompleto"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Crea un tacho guardándolo tanto en MySQL como en Neo4j",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tachos"
                ],
                "summary": "Crear un nuevo tacho",
                "parameters": [
                    {
                        "description": "Datos del tacho a crear",
                        "name": "tacho",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.CreateTachoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Tacho creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/services.CreateTachoResponse"
                        }
                    },
                    "400": {
                        "description": "Datos de entrada inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina un tacho tanto de MySQL como de Neo4j usando query parameters (custom_id O direccion+barrio)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tachos"
                ],
                "summary": "Eliminar un tacho",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID personalizado del tacho (direccion|barrio)",
                        "name": "custom_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Dirección del tacho (requiere también barrio)",
                        "name": "direccion",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Barrio del tacho (requerido si se pasa direccion)",
                        "name": "barrio",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tacho eliminado exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Parámetros inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Tacho no encontrado en ninguna base",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tachos/{id_tacho}/prioridad": {
            "put": {
                "description": "Actualiza el campo prioridad de un tacho en Neo4j",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tachos"
                ],
                "summary": "Actualizar prioridad del tacho",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del tacho",
                        "name": "id_tacho",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nueva prioridad del tacho",
                        "name": "prioridad",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdatePrioridadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Prioridad actualizada correctamente",
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdatePrioridadResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tachos/{id}/capacidad": {
            "put": {
                "description": "Actualiza el campo capacidad de un tacho en MySQL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tachos"
                ],
                "summary": "Actualizar capacidad del tacho",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del tacho",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nueva capacidad del tacho",
                        "name": "capacidad",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateCapacidadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Capacidad actualizada correctamente",
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateCapacidadResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.PersonaResponse": {
            "type": "object",
            "properties": {
                "camion_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "zona_id": {
                    "type": "string"
                }
            }
        },
        "handlers.RequestBody": {
            "type": "object",
            "properties": {
                "descripcion": {
                    "type": "string",
                    "example": "Incendio en edificio de oficinas"
                },
                "tipo": {
                    "type": "string",
                    "example": "incendio"
                }
            }
        },
        "handlers.ResponseBody": {
            "type": "object",
            "properties": {
                "descripcion": {
                    "type": "string",
                    "example": "Incendio en edificio de oficinas"
                },
                "message": {
                    "type": "string",
                    "example": "Emergencia enviada correctamente"
                },
                "tipo": {
                    "type": "string",
                    "example": "incendio"
                }
            }
        },
        "handlers.UpdateCapacidadRequest": {
            "type": "object",
            "properties": {
                "capacidad": {
                    "type": "number",
                    "example": 90
                }
            }
        },
        "handlers.UpdateCapacidadResponse": {
            "type": "object",
            "properties": {
                "capacidad": {
                    "type": "number",
                    "example": 90
                },
                "id_tacho": {
                    "type": "integer",
                    "example": 1
                },
                "message": {
                    "type": "string",
                    "example": "Capacidad actualizada correctamente"
                }
            }
        },
        "handlers.UpdatePrioridadRequest": {
            "type": "object",
            "properties": {
                "prioridad": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "handlers.UpdatePrioridadResponse": {
            "type": "object",
            "properties": {
                "id_neo": {
                    "type": "string"
                },
                "id_tacho": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "prioridad": {
                    "type": "integer"
                }
            }
        },
        "services.Camion": {
            "type": "object",
            "properties": {
                "id_camion": {
                    "type": "integer"
                },
                "nombre_tipo": {
                    "type": "string"
                },
                "tipo_estado": {
                    "type": "string"
                }
            }
        },
        "services.CamionResponse": {
            "type": "object",
            "properties": {
                "camion": {
                    "$ref": "#/definitions/services.Camion"
                }
            }
        },
        "services.CamionesResponse": {
            "type": "object",
            "properties": {
                "camiones": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.Camion"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "services.Centro": {
            "type": "object",
            "properties": {
                "barrio": {
                    "type": "string"
                },
                "direccion": {
                    "type": "string"
                },
                "id_centro": {
                    "type": "integer"
                },
                "id_neo": {
                    "type": "string"
                },
                "latitud": {
                    "type": "number"
                },
                "longitud": {
                    "type": "number"
                },
                "nombre": {
                    "description": "Información adicional de Neo4j",
                    "type": "string"
                },
                "nombre_tipo": {
                    "type": "string"
                }
            }
        },
        "services.CentroResponse": {
            "type": "object",
            "properties": {
                "centro": {
                    "$ref": "#/definitions/services.Centro"
                }
            }
        },
        "services.CentrosResponse": {
            "type": "object",
            "properties": {
                "centros": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.Centro"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "services.CreateTachoRequest": {
            "type": "object",
            "properties": {
                "barrio": {
                    "description": "Datos para Neo4j",
                    "type": "string"
                },
                "capacidad": {
                    "type": "number"
                },
                "direccion": {
                    "type": "string"
                },
                "id_estado": {
                    "type": "integer"
                },
                "id_tipo": {
                    "description": "Datos para MySQL",
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "prioridad": {
                    "type": "integer"
                }
            }
        },
        "services.CreateTachoResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "neo_node_id": {
                    "type": "string"
                },
                "tacho_id": {
                    "type": "integer"
                }
            }
        },
        "services.TachoCompleto": {
            "type": "object",
            "properties": {
                "barrio": {
                    "type": "string"
                },
                "capacidad": {
                    "type": "number"
                },
                "direccion": {
                    "type": "string"
                },
                "estado": {
                    "type": "string"
                },
                "id_tacho": {
                    "type": "integer"
                },
                "latitud": {
                    "type": "number"
                },
                "longitud": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "IntegracionDeAplicaciones2 API",
	Description:      "API para gestión de rutas y emergencias",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
