name: coverage

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-and-upload-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Debug - List test files
        working-directory: ./src/lambda/binService
        run: |
          echo "Current directory: $(pwd)"
          echo "Go files found:"
          find . -name "*.go" | head -10
          echo "Test files found:"
          find . -name "*_test.go"
          echo "Go mod info:"
          go mod download
          
      - name: Run tests with coverage
        working-directory: ./src/lambda/binService
        run: |
          go mod tidy
          go test -v ./... -covermode=atomic -coverpkg=./... -coverprofile=coverage.out
          echo "Coverage report generated"
          go tool cover -func=coverage.out | tail -n1
          
      - name: Debug - Check coverage file
        working-directory: ./src/lambda/binService
        run: |
          echo "Coverage file exists:"
          ls -la coverage.out || echo "Coverage file not found"
          echo "Coverage file content (first 10 lines):"
          head -10 coverage.out || echo "Cannot read coverage file"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./src/lambda/binService/coverage.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
