name: coverage

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-and-upload-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run tests with coverage
        working-directory: ./src/lambda/binService
        run: |
          go test ./... -covermode=atomic -coverpkg=./... -coverprofile=coverage.out
          go tool cover -func=coverage.out | tail -n1

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./src/lambda/binService/coverage.out
          flags: unittests
          name: codecov-umbrella
